<a href="https://colab.research.google.com/github/nmhom/MAT-422/blob/main/MAT422_HW_2.3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 2.3

In [3]:
import numpy as np
import pandas as pd
import math

## 2.3.1 Joint Probability Distributions
Joint probability is the probability of two or more events happening together. A joint probability distribution shows a probability distribution for two (or more) random variables.

### Define a Joint Probability Distribution

**Definition 2.3.1** Gives the probability that two discrete random variables take specific values at the same time. $$p(x,y) = P(X=x\,and\,Y=y)$$
All joint probabilities must be nonnegative and add up to 1.


In [4]:
# X = result of first die
# Y = result of the second die
# Build the full 6x6 joint PMF table
joint = np.full((6,6), 1/36)
print("Joint PMF (6x6, each cell = P(X=x, Y=y)):\n", joint)

# What is the probabilities that we roll a 3 on the first die and a 5 on the second die
print("\nP(X=3, Y=5):", joint[2,4]) # die shows 3, die shows 5
print("All probabilities nonnegative:", np.all(joint >= 0))
print("Sum of all probabilities:", joint.sum())

Joint PMF (6x6, each cell = P(X=x, Y=y)):
 [[0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]]

P(X=3, Y=5): 0.027777777777777776
All probabilities nonnegative: True
Sum of all probabilities: 1.0


### Calculate a Marginal PDF

**Marginal Distribution**: Gives the probability of one random variable without considering the value of the other variable
- To find a marginal probability, sum the joint probabilities over the other variable

**Definition 2.3.4** A marginal probability density function of X and Y, denoted by $f_x(x)$ and $f_y(y)$, respectively, are given by
$$f_x(x)=\int_{-\infty}^{\infty}f(x,y)dy \,\,for\,\, -\infty < x < \infty$$
$$f_y(y)=\int_{-\infty}^{\infty}f(x,y)dx \,\,for\,\, -\infty < y < \infty$$

In [15]:
# X = result of first die
# Y = result of the second die

joint_PDF = np.full((6,6), 1/36)
print("Joint PMF (6x6, each cell = P(X=x, Y=y)):\n", joint_PDF)

# Probability that we roll a 3 on the first die
# We don't care what number we roll on the second die
print("\nP(X=3):", joint_PDF[2].sum())

print("All probabilities nonnegative:", np.all(joint_PDF >= 0))
print("Sum of all probabilities:", joint_PDF.sum())

Joint PMF (6x6, each cell = P(X=x, Y=y)):
 [[0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]
 [0.02777778 0.02777778 0.02777778 0.02777778 0.02777778 0.02777778]]

P(X=3): 0.16666666666666669
All probabilities nonnegative: True
Sum of all probabilities: 1.0


### Calculate a Marginal PMF

**Definition 2.3.2** The marginal PMF gives the probability of one random variable while ignoring the other variables
- For X: sum over all possible values of Y $$p_X(x)=\Sigma_y p(x,y)$$
- For Y: sum over all possible values of X $$p_Y(y)=\Sigma_x p(x,y)$$

In [6]:
## Definition 2.3.2: marginal PMF, to get the probability of X = x, add the joint probabilities for that x across all possible Y's and vice versa for x
# Example:

p_X = joint.sum(axis = 1) # sum across each row
p_Y = joint.sum(axis = 0) # sum across each column

print("Marginal X:", p_X)
print("Marginal Y:", p_Y)
print("Each marginal should be 1/6:", np.allclose(p_X, 1/6), np.allclose(p_Y, 1/6))


Marginal X: [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Marginal Y: [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Each marginal should be 1/6: True True


### Define a Joint Distribution for Multiple Variables

**Definition 2.3.7**: A joint PMF describes the probability of a specific combination of two or more random variables

For discrete variables:
$p(x_1, x_2, ..., x_n) = P(X_1=x_1, X_2=x_2,..., X_n=x_n)$

In [7]:
# Three dice: p(2,4,6)
# Die 1 rolls a 2
# Die 2 rolls a 4
# Die 3 rolls a 6

p1 = p2 = p3 = 1/6
prob_2_4_6 = p1 * p2 * p3
print("P(Die1=2, Die2=4, Die3=6):", prob_2_4_6)

P(Die1=2, Die2=4, Die3=6): 0.004629629629629629


### Demonstrate Independence

**Definition 2.3.5** Two random variables X and Y are said to be independent if for every pair of x and y values, $$p(x,y) = p_x(x)*p_y(y)$$ when X and Y are discrete or $$f(x,y) = f_x(x) * f_y(y)$$ when X and Y are continuous. If the above is not satisfied for all (x,y), then X and Y are said to be dependent



In [8]:
p_x_eq3 = p_X[2]
p_y_eq5 = p_Y[4]

p_joint_3_5 = joint[2,4]
print("Independence check: p(3,5) == p_X(3)*p_Y(5)?", math.isclose(p_joint_3_5, p_x_eq3*p_y_eq5))

Independence check: p(3,5) == p_X(3)*p_Y(5)? True


## 2.3.2 Correlation and Dependence
When two random variables X and Y are not independent, it is frequently of interest to assess how strongly they are related to one another.



### Calculate Covariance

**Definition 2.3.9** Covariance measures how two random variables vary together
$$Cov(X,Y) = E[(X-\mu x)(Y-\mu y)]$$
- Positive covariance: X and Y tend to move in the same direction
- Negative covariance: X and Y tend to move in opposite directions
- Covariance near 0: Little/no linear relationship

In [18]:
x_hours_studied = np.array([1,2,3,4,5])
y_exam_score = np.array([60,65,70,80,85])

# population covariance
covariance = np.cov(x_hours_studied, y_exam_score, ddof=0)[0,1]

print(covariance)

13.0


### Calculate Correlation

**Definition 2.3.10** The correlation coefficient of X and Y, denoted by $$Corr(X,Y), \rho_{x,y}$$ or just $\rho$, is defined by $$\rho_{x,y}={Cov(X,Y)}/({\sigma_x * \sigma_y})$$
- Correlation is always between -1 and 1
- $\rho = 1$: perfect positive linear relationship
- $\rho = -1$: perfect negative linear relationship
- $\rho = 0$: no linear relationship
If X and Y are independent:
- X and Y independent: $\rho = 0$, but $\rho = 0$ does not necessarily mean X and Y are independent. Correlation only measures linear relationships

In [19]:
# population correlation
correlation = np.corrcoef(x_hours_studied,y_exam_score)[0,1]
print("Correlation:", correlation)

Correlation: 0.9912407071619304


### Calculate Sample Covariance
$$s_{xy}=1/(n-1)\,\Sigma_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})$$

In [20]:
# as X increases, Y increases too, so the covariance is positive

sample_covariance = np.cov(x_hours_studied,y_exam_score)[0,1]
print(sample_covariance)

16.25


### Calculate Sample Correlation

In [10]:
# sample correlation
r = np.corrcoef(x_hours_studied,y_exam_score)[0,1]
print("Sample correlation:", r)

# negative correlation example
x_1 = np.array([1,2,3,4,5])
y_1 = np.array([10,9,8,7,6])
neg_cov = np.cov(x_1,y_1)[0,1]
print(neg_cov)

0.9999999999999999
-2.5


## 2.3.3 Random Samples
A random sample is a group of observations that are independent and come from the same population/distribution.

A random sample of size n consists of random variables X1,...,Xn that:
1. Are independent of each other
2. Have the same probability distribution

### Define a Random Sample

In [11]:
population = [1,2,3,4,5,6] # die outcomes = the population
pop_mean = np.mean(population)
pop_std = np.std(population)
print("Population mean:", pop_mean, " Population std:", pop_std)

n = 30
sample = np.random.choice(population, size=n, replace=True)
print("Random sample of size", n, ":", sample)

Population mean: 3.5  Population std: 1.707825127659933
Random sample of size 30 : [2 6 5 3 2 6 2 2 4 3 5 3 2 3 6 1 3 6 2 5 6 1 4 1 5 3 2 2 6 4]


### Calculate the Sample Mean

Sample Mean
- The sample mean is the average of the observations:
$$\bar{X} = (X_1+...+X_n)/n$$ The sample mean is used to estimate the population mean $\mu$

As the sample size n gets larger: $\sigma_{\bar{X}} = (\sigma)/\sqrt{n}$ gets smaller

The sample mean is centered around the population mean, and its variability gets smaller as the sample size increases.
$$E(\bar{X}) = \mu$$

$$V(\bar{X}) = \frac{\sigma^2}{n}$$

$$\sigma_{\bar{X}} = \frac{\sigma}{\sqrt{n}}$$

In [12]:
sample_mean = np.mean(sample)
print("Sample mean:", sample_mean, " (should be close to population mean", pop_mean, ")")

# demonstrate sigma_xbar = sigma/sqrt(n) by simulating many sample means
means = [np.mean(np.random.choice(population, size=n, replace=True)) for _ in range(10000)]
print("Simulated std of sample means:", np.std(means))
print("Theoretical sigma/sqrt(n):", pop_std/np.sqrt(n))

Sample mean: 3.5  (should be close to population mean 3.5 )
Simulated std of sample means: 0.3172542203729439
Theoretical sigma/sqrt(n): 0.31180478223116176


### Calculate the Sample Total

Sample Total: The sample total is $$T_0=X_1+...+X_n$$ its properties are: $$E(T_0)=n\mu$$ $$V(T_0)=n\sigma^2$$ $$\sigma_{T_0} = \sqrt{n}\sigma$$

In [13]:
sample_total = np.sum(sample)
print("Sample total:", sample_total, " (E(T) = n*mu =", n*pop_mean, ")")

totals = [np.sum(np.random.choice(population, size=n, replace=True)) for _ in range(10000)]
print("Simulated mean of totals:", np.mean(totals), " vs n*mu:", n*pop_mean)
print("Simulated std of totals:", np.std(totals), " vs sqrt(n)*sigma:", np.sqrt(n)*pop_std)

Sample total: 105  (E(T) = n*mu = 105.0 )
Simulated mean of totals: 105.0175  vs n*mu: 105.0
Simulated std of totals: 9.298042468713508  vs sqrt(n)*sigma: 9.354143466934854


### Demonstrate the Central Limit Theorem

**2.3.3.2 Central Limit Theorem**: Even if the original population is not normally distributed, the distribution of the sample mean becomes approximately normal when the sample size is sufficiently large.

For a large $n$:

$$\bar{X} \approx N\left(\mu,\frac{\sigma^2}{n}\right)$$

- Mean of $\bar{X}$: $\mu$
- Variance of $\bar{X}$: $\frac{\sigma^2}{n}$
- Standard deviation of $\bar{X}$: $\frac{\sigma}{\sqrt{n}}$

The larger the sample size $n$, the better the normal approximation.

In [14]:
# The original population (a die roll) is uniform, NOT normal --
# CLT says the sample MEAN still becomes approximately normal as n grows.
small_n = 5
large_n = 50
means_small = [np.mean(np.random.choice(population, size=small_n, replace=True)) for _ in range(5000)]
means_large = [np.mean(np.random.choice(population, size=large_n, replace=True)) for _ in range(5000)]

print("n=5  -> std of means:", np.std(means_small), " theory:", pop_std/np.sqrt(small_n))
print("n=50 -> std of means:", np.std(means_large), " theory:", pop_std/np.sqrt(large_n))

n=5  -> std of means: 0.761317914146252  theory: 0.7637626158259733
n=50 -> std of means: 0.24233239423568612  theory: 0.24152294576982397
