<a href="https://colab.research.google.com/github/nmhom/MAT-422/blob/main/mat422_HW_1.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HW 1.4

In [2]:
import numpy as np
from scipy.linalg import null_space

## 1.4.1 Singular Value Decomposition (SVD)

SVD factorizes any m x n matrix A into the product of three simpler matrices: $$ A = U\Sigma V^T $$

This section demonstrates the core definitions behind Singular Value Decomposition: SVD breaks a matrix into $A = U\Sigma V^T$, checking the singular values that come from $A^TA$, checking how much A stretches a direction from a singular value, and how the number of nonzero singular values is equal to the rank.

### SVD breaks a matrix into $A = UΣV^T$

**Theorem 1.4.2** Every matrix can be decomposed as $A = UΣV^T$.

In [6]:
u = np.array([1, 0, 0])
v = np.array([0,1,0])
x = np.array([0,0,1])
A = np.column_stack((u, v, x))

U, S, VT = np.linalg.svd(A)
print(A)
print("U (matrix of left singular vectors) = ", U)
print("S (matrix containing the singular values) = ", S)
print("VT (matrix of right singular vectors) = ", VT)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
U (matrix of left singular vectors) =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
S (matrix containing the singular values) =  [1. 1. 1.]
VT (matrix of right singular vectors) =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Singular values come from $A^TA$

In [10]:
eigenvalues, eigenvectors = np.linalg.eigh(A.T @ A)
print("Eigenvalues: ", eigenvalues)
print()
print("Eigenvectors: ", eigenvectors)

Eigenvalues:  [1. 1. 1.]

Eigenvectors:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Singular values tell you how much A stretches a direction

$$||Av_i||=\sigma_i$$

In [15]:
# 1. Find v_i, an eigenvector of A^TA
eigenvalues, eigenvectors = np.linalg.eigh(A.T @ A)

# Select the first eigenvector for demonstration
v_i = eigenvectors[:, 0]

# 2. Calculate Av_i
Av_i = A @ v_i

# 3. Find the length of Av_i
length = np.linalg.norm(Av_i)

print("Av_i: ", Av_i)
print("Length of Av_i: ", length)

Av_i:  [1. 0. 0.]
Length of Av_i:  1.0


### Number of nonzero singular values = rank

**Theorem 1.4.1** rank(A) = r, if A has r nonzero singular values.

## 1.4.2 Low-Rank Matrix Approximations

Low-rank approximation is a mathematical method used to replace a large, complex data matrix with a smaller, simplified matrix of lower rank while keeping the most important information. This section demonstrates the core definitions behind low-rank matrix approximations: determining how an SVD breaks a matrix into components, learning how low-rank approx. means keaping only the most important components, and checking to see that the approximation error is the next singular value.


### SVD breaks a matrix into components
$$
A = \sum_{i=1}^{r} \sigma_i u_i v_i^T
$$
S contains the singular values like $\sigma_1, \sigma_2, ...,\sigma_n$. The larger the singular value, the more important component.

In [16]:
U, S, VT = np.linalg.svd(A)

print("S (matrix containing the singular values) = ", S)


S (matrix containing the singular values) =  [1. 1. 1.]


### Low-rank approximation means keeping only the most important components

The truncated SVD is:
$$
A_k=\sum_{i=1}^{k} \sigma_i u_i v_i^T
$$

### Induced 2-norm measures the maximum stretching

**Definition 1.4.3** The induced 2-norm measures the maximum amount that matrix A can stretch a vector. It can also be used to measure the error between two matrices.

In [17]:
# Choose k (the number of components you want to keep)
k = 2

# Take the first k pieces of the SVD and put them back together
Ak = U[:,:k] @ np.diag(S[:k]) @ VT[:k,:]

# The rank-k approximation
print("Ak = ", Ak)

Ak =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


### The approximation error is the next singular value

**Lemma 1.4.4** The error you get from keeping the first k components is exactly the next singular value
 $$\|A-A_k\|_2=\sigma_{k+1}$$

In [19]:
error = np.linalg.norm(A - Ak, 2)
print(error)

is_equal = np.allclose(error, S[k])
print(is_equal)

1.0
True


### Truncated SVD gives the best possible low-rank approximation

**Theorem 1.4.5** Eckart-Young Mirsky $||A - A_k||_2 <= ||A - B||_2$ for any B with: rank(B) <= k

No other rank-k approximation can do better than $A_k$



## 1.4.3 Principal Component Analysis

Principal Component Analysis (PCA) is a statistical method used to simplify large, complex datasets by reducing the number of variables while retaining as much important information as possible. This section demonstrates the core functionality behind PCA: learning how PCA finds the directions of maximum variance, how PCA uses eigendecomposition of the covariance matrix to find those directions, and learning how PCA can reduce dimensions while preserving as much variance as possible.

### PCA finds the directions of maximum variance

### PCA uses eigendecomposition of the covariance matrix to find those directions

### PCA can reduce dimensions while preserving as much variance as possible